# Makefile
all:


Fibonacci: Fibonacci.c
	gcc Fibonacci.c -o Fibonacci.out

count_vowels: count_vowels.c
	gcc count_vowels.c -o count_vowels.out

count_ones: count_ones.c
	gcc count_ones.c -o count_ones.out


clean:
	rm -f *.out
	# rm *~ #*#
