# Makefile
all:


Fibonacci: Fibonacci.c
	gcc Fibonacci.c -o Fibonacci.out

count_vowels: count_vowels.c
	gcc count_vowels.c -o count_vowels.out

count_ones: count_ones.c
	gcc count_ones.c -o count_ones.out

a4_minus_b4: a4_minus_b4.c
	gcc a4_minus_b4.c -o a4_minus_b4.out

swap_bytes: swap_bytes.c
	gcc -g swap_bytes.c -o swap_bytes.out

clean:
	rm -f *.out
	# rm *~ #*#
