all:


global_vars: global_vars.c
	gcc -g -std=c89 -o0 global_vars.c -o global_vars

malloc_limits: malloc_limits.c
	gcc -g -std=c89 -o0 malloc_limits.c -o malloc_limits

malloc_vars: malloc_vars.c
	gcc -g -std=c89 -o0 malloc_vars.c -o malloc_vars 

static_vars: static_vars.c
	gcc -g -std=c89 -o0 static_vars.c -o static_vars

clean: 
	rm -f global_vars malloc_limits malloc_vars static_vars
